env:
  - EXAMPLE=simple-player
  - EXAMPLE=qml-player

language: cpp

before_install: . tools/ci/linux/before_install.sh
install: . tools/ci/linux/install.sh
script: . tools/ci/linux/script.sh
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && . tools/ci/linux/after_success.sh || true'

addons:
  apt:
   sources:
    - ubuntu-toolchain-r-test
   packages:
    - gcc-4.8
    - g++-4.8
    - libqt4-dev
    - libvlc-dev
    - libvlccore-dev
    - vlc
    - p7zip-full
